name: "NixOS_Live"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - name: Build NixOS live image
        run: |
          nix build '.#nixosConfigurations.exampleHost.config.system.build.isoImage'
          echo build success
      - uses: actions/upload-artifact@v3
        with:
          name: nixos-live-image
          path: result/iso/